### ISSUE TITLE
如何通知别人

### ISSUE THREAD

**Issue by JoyChou93** [YianAndCode/Comment2Wechat#1]
如果别人评论后，现在能给自己发微信通知，但是如果你回复给别人后，别人应该收不到什么通知。

**Comment by YianAndCode** [comment]
这个目前确实是无法实现的。

访客评论之后如果也想收到微信通知，那么他就需要也绑定他的微信，如果是基于 Server 酱的话，这个操作是比较麻烦而且是不安全（试想，你在别人博客评论并且希望收到微信通知，那么你需要把你在 Server 酱的 secret 交给别人，别人要是居心不良，就可以给你发骚扰消息了）的；

如果你真的想实现的话，可以用类似的方式，通过自己的服务号（个人身份无法注册）/接口测试号（限制比较多）来推送模板消息，这样就需要对 Typecho 做比较大的改造了。
