### ISSUE TITLE
是否能增加文章标题和评论一起推送的功能呢

### ISSUE THREAD

**Issue by YomiPixel** [YianAndCode/Comment2Wechat#2]
这样会更直观吧……

**Comment by YianAndCode** [comment]
很早之前就有计划了，只不过一直没有时间，可能近期内会加上

**Comment by wuhuisai** [comment]
我自己修改了一下，哈哈哈哈

**Comment by YianAndCode** [comment]
@wuhuisai 欢迎提 PR（逃😂

**Comment by wuhuisai** [comment]
$text = "网站收到新评论:";
$desp = "**".$comment['author']."** 在 [".$post->title."](".$post->permalink." \"".$post->title."\") 中说到: \n\n ------------ \n\n ".$comment['text'];

**Comment by wuhuisai** [comment]
```
$text = "网站收到新评论:";
$desp = "**".$comment['author']."** 在 [".$post->title."](".$post->permalink." \"".$post->title."\") 中说到: \n\n ------------ \n\n ".$comment['text'];
```

**Comment by YianAndCode** [comment]
@wuhuisai 感谢！
@YomiPixel 已提交 v1.1 更新，欢迎到 release 页下载~
